apiVersion: v1
kind: Service
metadata:
  name: gamebot
  labels:
    name: gamebot    
spec:
  selector:
    name: gamebot    
  type: LoadBalancer
  ports:
   - port: 80
     name: gamebot
     targetPort: 8080
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamebot
spec:
  replicas: 5
  selector:
    matchLabels:
      name: gamebot      
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: gamebot        
    spec:
      imagePullSecrets:
        - name: team5-docker
      containers:
      - name: gamebot
        image: team5acr67a0c9.azurecr.io/gamebot:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: gamebot         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "8080"
          - name: "PICK_STRATEGY"
            value: "RANDOM"
          - name: "APPINSIGHTS_INSTRUMENTATIONKEY"
            value: "de07e1ac-a3ac-473a-907e-d795006a3e41"      
          - name: "FF_BETS"      
            value: "TEST"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
